version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.11.5
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123qwe
      - MYSQL_ROOT_PASSWORD=123qwe
    volumes:
      - ./docker/mariadb:/var/lib/mysql
